
#--------------------------------------------------- AGC ---------------------------------------------------
G_AGC_1_ALL_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/agc-0.1-1-no.28 is 0.1.csv",header = T)
G_AGC_1_T_ALL_1 <- rowMeans(G_AGC_1_ALL_1[,1:30])
G_AGC_1_ONE_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/agc-0.1-1-no.28 is 0.8.csv",header = T)
G_AGC_1_T_ONE_8 <- rowMeans(G_AGC_1_ONE_8[,1:30])
G_AGC_1_ONE_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/agc-0.8-1-no.28 is 0.1.csv",header = T)
G_AGC_1_T_ONE_1 <- rowMeans(G_AGC_1_ONE_1[,1:30])
G_AGC_1_ALL_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/agc-0.8-1-no.28 is 0.8.csv",header = T)
G_AGC_1_T_ALL_8 <- rowMeans(G_AGC_1_ALL_8[,1:30])

plot(G_AGC_1_T_ONE_1,type="l",col="deepskyblue1", lty=2, lwd=2,xlab="Iteration", ylab="Social Cost",xlim=c(0, 1000), ylim=c(10000, 16000))
lines(G_AGC_1_T_ALL_8,type="l",col="firebrick2", lty=2, lwd=2)
lines(G_AGC_1_T_ALL_1,type="l",col="seagreen3",lty=5, lwd=2)
lines(G_AGC_1_T_ONE_8,type="l",col="darkorange", lty=4, lwd=2,lend = 0)
abline(h=16038.17,type="l",col="magenta2", lty=1, lwd=2)
title(main='Social Cost, AGC Type 1',xlab="Iteration", ylab="Social Cost",lwd=3)

#--------------------------------------------------- BI ---------------------------------------------------
G_BI_1_ALL_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_BI-0.1-1-no.28 is 0.1.csv",header = T)
G_BI_1_T_ALL_1 <- rowMeans(G_BI_1_ALL_1[,1:30])
G_BI_1_ONE_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_BI-0.1-1-no.28 is 0.8.csv",header = T)
G_BI_1_T_ONE_8 <- rowMeans(G_BI_1_ONE_8[,1:30])
G_BI_1_ONE_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_BI-0.8-1-no.28 is 0.1.csv",header = T)
G_BI_1_T_ONE_1 <- rowMeans(G_BI_1_ONE_1[,1:30])
G_BI_1_ALL_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_BI-0.8-1-no.28 is 0.8.csv",header = T)
G_BI_1_T_ALL_8 <- rowMeans(G_BI_1_ALL_8[,1:30])

plot(G_BI_1_T_ONE_1,type="l",col="deepskyblue1", lty=2, lwd=2,xlab="Iteration", ylab="Social Cost",xlim=c(0, 1000), ylim=c(10000, 16000))
lines(G_BI_1_T_ALL_8,type="l",col="firebrick2", lty=2, lwd=2)
lines(G_BI_1_T_ALL_1,type="l",col="seagreen3",lty=5, lwd=2)
lines(G_BI_1_T_ONE_8,type="l",col="darkorange", lty=4, lwd=2)
abline(h=16038.17,type="l",col="magenta2", lty=1, lwd=2)
title(main='Social Cost, SM_AGC_BI Type 1',xlab="Iteration", ylab="Social Cost",lwd=3)

#--------------------------------------------------- CI ---------------------------------------------------
G_CI_1_ALL_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_CI-0.1-1-no.28 is 0.1.csv",header = T)
G_CI_1_T_ALL_1 <- rowMeans(G_CI_1_ALL_1[,1:30])
G_CI_1_ONE_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_CI-0.1-1-no.28 is 0.8.csv",header = T)
G_CI_1_T_ONE_8 <- rowMeans(G_CI_1_ONE_8[,1:30])
G_CI_1_ONE_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_CI-0.8-1-no.28 is 0.1.csv",header = T)
G_CI_1_T_ONE_1 <- rowMeans(G_CI_1_ONE_1[,1:30])
G_CI_1_ALL_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_CI-0.8-1-no.28 is 0.8.csv",header = T)
G_CI_1_T_ALL_8 <- rowMeans(G_CI_1_ALL_8[,1:30])

plot(G_CI_1_T_ONE_1,type="l",col="deepskyblue1", lty=2, lwd=2,xlab="Iteration", ylab="Social Cost",xlim=c(0, 1000), ylim=c(10000, 16000))
lines(G_CI_1_T_ALL_8,type="l",col="firebrick2", lty=2, lwd=2)
lines(G_CI_1_T_ALL_1,type="l",col="seagreen3",lty=5, lwd=2)
lines(G_CI_1_T_ONE_8,type="l",col="darkorange", lty=4, lwd=2)
abline(h=16038.17,type="l",col="magenta2", lty=1, lwd=2)
title(main='Social Cost, SM_AGC_CI Type 1',xlab="Iteration", ylab="Social Cost",lwd=3)

#--------------------------------------------------- T_BI ---------------------------------------------------
G_T_BI_1_ALL_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T_BI-0.1-1-no.28 is 0.1.csv",header = T)
G_T_BI_1_T_ALL_1 <- rowMeans(G_T_BI_1_ALL_1[,1:30])
G_T_BI_1_ONE_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T_BI-0.1-1-no.28 is 0.8.csv",header = T)
G_T_BI_1_T_ONE_8 <- rowMeans(G_T_BI_1_ONE_8[,1:30])
G_T_BI_1_ONE_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T_BI-0.8-1-no.28 is 0.1.csv",header = T)
G_T_BI_1_T_ONE_1 <- rowMeans(G_BI_1_ALL_8[,1:30])
G_T_BI_1_ALL_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T_BI-0.8-1-no.28 is 0.8.csv",header = T)
G_T_BI_1_T_ALL_8 <- rowMeans(G_T_BI_1_ALL_8[,1:30])

plot(G_T_BI_1_T_ONE_1,type="l",col="deepskyblue1", lty=2, lwd=2,xlab="Iteration", ylab="Social Cost",xlim=c(0, 1000), ylim=c(10000, 16000))
lines(G_T_BI_1_T_ALL_8,type="l",col="firebrick2", lty=2, lwd=2)
lines(G_T_BI_1_T_ALL_1,type="l",col="seagreen3",lty=5, lwd=2)
lines(G_T_BI_1_T_ONE_8,type="l",col="darkorange", lty=4, lwd=2)
abline(h=16038.17,type="l",col="magenta2", lty=1, lwd=2)
title(main='Social Cost, SM_AGC_T_BI Type 1',xlab="Iteration", ylab="Social Cost",lwd=3)

#--------------------------------------------------- T_CI ---------------------------------------------------
G_T_CI_1_ALL_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T_CI-0.1-1-no.28 is 0.1.csv",header = T)
G_T_CI_1_T_ALL_1 <- rowMeans(G_T_CI_1_ALL_1[,1:30])
G_T_CI_1_ONE_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T_CI-0.1-1-no.28 is 0.8.csv",header = T)
G_T_CI_1_T_ONE_8 <- rowMeans(G_T_CI_1_ONE_8[,1:30])
G_T_CI_1_ONE_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T_CI-0.8-1-no.28 is 0.1.csv",header = T)
G_T_CI_1_T_ONE_1 <- rowMeans(G_T_CI_1_ONE_1[,1:30])
G_T_CI_1_ALL_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T_CI-0.8-1-no.28 is 0.8.csv",header = T)
G_T_CI_1_T_ALL_8 <- rowMeans(G_T_CI_1_ALL_8[,1:30])

plot(G_T_CI_1_T_ONE_1,type="l",col="deepskyblue1", lty=2, lwd=2,xlab="Iteration", ylab="Social Cost",xlim=c(0, 1000), ylim=c(10000, 16000))
lines(G_T_CI_1_T_ALL_8,type="l",col="firebrick2", lty=2, lwd=2)
lines(G_T_CI_1_T_ALL_1,type="l",col="seagreen3",lty=5, lwd=2)
lines(G_T_CI_1_T_ONE_8,type="l",col="darkorange", lty=4, lwd=2)
abline(h=16038.17,type="l",col="magenta2", lty=1, lwd=2)
title(main='Social Cost, SM_AGC_T_CI Type 1',xlab="Iteration", ylab="Social Cost",lwd=3)

#--------------------------------------------------- T_ ---------------------------------------------------
G_T_1_ALL_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T-0.1-1-no.28 is 0.1.csv",header = T)
G_T_1_T_ALL_1 <- rowMeans(G_T_1_ALL_1[,1:30])
G_T_1_ONE_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T-0.1-1-no.28 is 0.8.csv",header = T)
G_T_1_T_ONE_8 <- rowMeans(G_T_1_ONE_8[,1:30])
G_T_1_ONE_1 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T-0.8-1-no.28 is 0.1.csv",header = T)
G_T_1_T_ONE_1 <- rowMeans(G_T_1_ONE_1[,1:30])
G_T_1_ALL_8 <- read.csv("C:/MARTIN/BEER SHEVA/מערכת/Basics/a-1/SM_AGC_T-0.8-1-no.28 is 0.8.csv",header = T)
G_T_1_T_ALL_8 <- rowMeans(G_T_1_ALL_8[,1:30])

plot(G_T_1_T_ONE_1,type="l",col="deepskyblue1", lty=2, lwd=2,xlab="Iteration", ylab="Social Cost",xlim=c(0, 1000), ylim=c(10000, 16000))
lines(G_T_1_T_ALL_8,type="l",col="firebrick2", lty=2, lwd=2)
lines(G_T_1_T_ALL_1,type="l",col="seagreen3",lty=5, lwd=2)
lines(G_T_1_T_ONE_8,type="l",col="darkorange", lty=4, lwd=2)
abline(h=16038.17,type="l",col="magenta2", lty=1, lwd=2)
title(main='Social Cost, SM_AGC_T Type 1',xlab="Iteration", ylab="Social Cost",lwd=3)
